### ISSUE TITLE
drop gap from 15.4

### ISSUE THREAD

**Issue by lkocman** [openSUSE/release-notes-openSUSE#114]
Request to drop gap is here https://code.opensuse.org/leap/features/issue/24, let's make sure that we cover it in RN as well.

Context from Wolfgang:

Got in touch with Jan Engelhardt and he mentioned that gap was removed from Factory because it isn't FHS-compliant and upstream refused to change that.
The old version (as it is in Leap 15.2 and Backports) was working but new version might not.

So I guess it is better to remove it completely from Leap/Backports.

**Comment by lkocman** [comment]
https://build.opensuse.org/request/show/909795

**Comment by KucharczykL** [comment]
Is it enough to say that the `gap` package was removed or should we also mention the reason?

**Comment by lkocman** [comment]
Just to mention that it was removed. I left it as a todo for myself :-) we have to branch RN for 15.4 anyway.

**Comment by KucharczykL** [comment]
Done in #115
