### ISSUE TITLE
"gap" package removal mentions "artha" bug link

### ISSUE THREAD

**Issue by elchevive** [openSUSE/release-notes-openSUSE#119]
Hi,

In the "gap" package removal note:

<package>gap</package>: Removed because the package is not FHS-compliant. For more information, see <link xlink:href="https://bugzilla.opensuse.org/show_bug.cgi?id=1143860"/>.

The bugzilla link mentions "artha" package removal (you can see this in the screnshoot below)

![image](https://user-images.githubusercontent.com/1202332/156174033-86583ab0-3715-4510-a362-9cb6a1600f7c.png)

**Comment by KucharczykL** [comment]
Thank you for reporting this! I have replaced it with the correct link.
