### ISSUE TITLE
getting 404 for part-basics.html

### ISSUE THREAD

**Issue by lkocman** [openSUSE/release-notes-openSUSE#133]
We're getting 404 after clicking on 
https://doc.opensuse.org/documentation/leap/startup/html/book.opensuse.startup/part-basics.html

Which is referenced from RN.
https://doc.opensuse.org/release-notes/x86_64/openSUSE/Leap/15.5/index.html#installation

Either we should make particular docs available again or drop the references.

**Comment by fsundermeyer** [comment]
This has already been fixed with 7a833889f8a682e3. butapparently not neen published

**Comment by KucharczykL** [comment]
I've updated https://build.opensuse.org/package/show/Documentation:Auto/release-notes-openSUSE_Leap_15.5 but I think it doesn't update the files on the server automatically anymore because the changes haven't propagated to the website.
