### ISSUE TITLE
Link in README.md not working

### ISSUE THREAD

**Issue by stacheldrahtje** [openSUSE/release-notes-openSUSE#149]
Hi, 

The first link on this line is not working. Where is it supposed to link to?

https://github.com/openSUSE/release-notes-openSUSE/blob/4be4a2c8df56ac45dda28aa78a7cedc1543893d3/README.md?plain=1#L86

Should it be this link? https://doc.opensuse.org/release-notes/x86_64/openSUSE/Leap/15.6/index.html

Kind regards,

Natasha

**Comment by KucharczykL** [comment]
From the context it seems it should link to https://doc.opensuse.org without any specific document.
