### ISSUE TITLE
Word is missing from string

### ISSUE THREAD

**Issue by scootergrisen** [openSUSE/release-notes-openSUSE#65]
Seems like a word or something is missing in this string:
https://github.com/openSUSE/release-notes-openSUSE/blob/master/xml/release-notes.xml#L210(para)

Maybe it should be "moved from the ... to the ..." or "moved from the ... and ...".

**Comment by sknorr** [comment]
I have fixed the immediate issue by adding "to"/

However, @lnussel, do we need this entry ("CUPS Version Upgrade to 1.7") at all at this point?

**Comment by lnussel** [comment]
I don't think so. Was only relevant for 42, nowadays that is old news.

**Comment by sknorr** [comment]
Thanks! Have removed the entry entirely.
