### ISSUE TITLE
german Versionshinweise wrong

### ISSUE THREAD

**Issue by peterdd** [openSUSE/release-notes-openSUSE#81]
https://en.opensuse.org/openSUSE:Release_Notes
shows current opensuse 15.1, but when I use the link 'Deutsch' the german site an old version: https://de.opensuse.org/Versionshinweise

Further: Following the 'latest' link to https://doc.opensuse.org/release-notes/x86_64/openSUSE/Leap/42.3/RELEASE-NOTES.de.html
it shows 'Veröffentlicht: 2019-07-01'
And the first sentence below:
'Das Ende der Betreuungszeit für openSUSE Leap 42.3 wurde jetzt erreicht.'

WTF. So released and end support date on the same day? ;-)

Well, this versioning with leap, tumbleweed, 42, 13, 15 is soo annoying/confusing. Stick to normal versioning 15, 15.1, ... please. Even renaming the '42er' releases to something 14? would help. 

BTW: It would be great to have an official opensuse 15.1 vagrant box or documented how to **reproducible build** it.

https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=updated&provider=virtualbox&q=opensuse+15.1

**Comment by sknorr** [comment]
* Link is fixed now. Note that de.opensuse.org is a wiki -- if you see something wrong, just go and edit it away.
* The main page of doc.opensuse.org is usually the most reliable way to get to the release notes for the product released most recently. 
* The publication date displayed is for the release notes and not for the product as such.
* The 42.x series is now unmaintained. Retroactively renaming it is a non-starter. The naming scheme is admittedly quirky, but it works as follows:
  * openSUSE Tumbleweed is a rolling release and the only version number there is the build date of each openSUSE Tumbleweed snapshot image
  * For Leap, the version numbering looks like this: ... -> openSUSE 12.x -> openSUSE 13.x -> openSUSE Leap 42.x -> openSUSE Leap 15.x
  * The Leap versioning was chosen to allow better coordination between openSUSE and SUSE Linux Enterprise (with Leap 42.x ~ SLE 12 SPx and Leap 15.x ~ SLE 15 SPx)
* I can't help with Vagrant, please ask on a mailing list like opensuse-factory@opensuse.org
